- name: Import the Datadog Agent role from the Datadog collection
  ansible.builtin.import_role:
    name: datadog.dd.agent
  vars:
    datadog_api_key: "{{ DATADOG_API_KEY }}"
    datadog_site: "{{ DATADOG_SITE }}"
    datadog_config:
      logs_enabled: true

- name: Datadog logging config
  ansible.builtin.copy:
    src: files/journald.d_conf.yaml
    dest: /etc/datadog-agent/conf.d/journald.d/conf.yaml
    owner: dd-agent
    group: dd-agent
    datadog_additional_groups: "systemd-journal"
    datadog_checks:
      journald:
        logs:
          - type: journald
            path: /var/log/journal/

- name: Reload datadog
  ansible.builtin.systemd_service:
    name: datadog-agent
    state: restarted
    enabled: true
    daemon_reload: true
