- name: Copy longhorn manifiest
  ansible.builtin.copy:
    src: ./templates/longhorn_manifest.yaml.j2
    dest: /root/longhorn_manifest.yaml
    owner: root
    group: root
    mode: "0600"

- name: Apply longhorn manifest
  ansible.builtin.command:
    chdir: /root/
    cmd: kubectl apply -f longhorn_manifest.yaml

- name: Copy datadog operator manifiest
  ansible.builtin.template:
    src: datadog_operator.yaml.j2
    dest: /root/datadog_operator.yaml
    owner: root
    group: root
    mode: "0600"

- name: Apply datadog operator manifest
  ansible.builtin.command:
    chdir: /root/
    cmd: kubectl apply -f datadog_operator.yaml

- name: Copy datadog agent manifiest
  ansible.builtin.template:
    src: datadog_agent.yaml.j2
    dest: /root/datadog_agent.yaml
    owner: root
    group: root
    mode: "0600"

- name: Apply datadog agent manifest
  ansible.builtin.command:
    chdir: /root/
    cmd: kubectl apply -f datadog_agent.yaml

- name: Copy traefik config
  ansible.builtin.template:
    src: traefik_config.yaml.j2
    dest: /root/traefik_config.yaml
    owner: root
    group: root
    mode: "0600"

- name: Apply traefik config manifest
  ansible.builtin.command:
    chdir: /root/
    cmd: kubectl apply -f traefik_config.yaml
