apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    credentials:
      apiSecret:
        secretName: datadog-api-key
        keyName: api-key
  features:
    apm:
      enabled: true
    logCollection:
      enabled: true
