- hosts: mgrs:workers 
  become: true
  roles:
    - role: meshdb-k8s-node
    - role: k3s.orchestration.prereq # k3s-ansible
    - role: k3s.orchestration.k3s_agent # k3s-ansible
  vars:
    k3s_version: v1.30.2+k3s2
    api_endpoint: "{{ K3S_API_ENDPOINT }}"
    token: "{{ K3S_TOKEN }}"
    extra_server_args: ""
    extra_agent_args: ""

- hosts: mgrs 
  become: true
  roles:
    - role: meshdb-mgr
    - role: k3s.orchestration.prereq # k3s-ansible
    - role: k3s.orchestration.k3s_server # k3s-ansible
  vars:
    k3s_version: v1.30.2+k3s2
    api_endpoint: "{{ K3S_API_ENDPOINT }}"
    token: "{{ K3S_TOKEN }}"
    extra_server_args: ""
    extra_agent_args: ""

- hosts: lb
  become: true
  roles:
    - role: k8s-lb
