- hosts: mgrs 
  become: true
  roles:
    - role: mesh-k8s-node
    - role: mesh-mgr
    - role: k3s.orchestration.prereq # k3s-ansible
    - role: k3s.orchestration.k3s_server # k3s-ansible
    - role: k8s-cluster-helm
  vars:
    k3s_version: v1.30.2+k3s2
    api_endpoint: "{{ K3S_API_ENDPOINT }}"
    token: "{{ K3S_TOKEN }}"
    extra_server_args: ""
    extra_agent_args: ""
    server_group: "mgrs"

- hosts: workers 
  become: true
  roles:
    - role: mesh-k8s-node
    - role: k3s.orchestration.prereq # k3s-ansible
    - role: k3s.orchestration.k3s_agent # k3s-ansible
  vars:
    k3s_version: v1.30.2+k3s2
    api_endpoint: "{{ K3S_API_ENDPOINT }}"
    token: "{{ K3S_TOKEN }}"
    extra_server_args: ""
    extra_agent_args: ""

- hosts: lb
  become: true
  roles:
    - role: k8s-lb
