name: Deploy Environments
permissions: read-all

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    branches:
      - dev

jobs:
  deploy_dev3:
    name: Deploy dev3
    uses: ./.github/workflows/deploy_k8s_cluster.yaml
    with:
      environment: dev3
    secrets: inherit
    if: github.ref == 'refs/heads/main'
